---
title: "Week 4 in class"
output: html_notebook
---

```{r}
library(tidyverse)
library(mosaic)
library(broom)
set.seed(42)

prop <- 0.4
pop <- 100000
sample <- 5000

prop_pop <- function(p,n){ return( data.frame(x = c(rep(1, n * p), rep(0, n-(n * p)))) ) }
pn <- prop_pop(prop, pop)
```

```{r}
n20 <- do(sample) * mean(~x, data = pn %>% sample_n(20, replace = F))
n100 <- do(sample) * mean(~x, data = pn %>% sample_n(100, replace = F))
n300 <- do(sample) * mean(~x, data = pn %>% sample_n(300, replace = F))
```

```{r, warning=FALSE}
df <- data.frame('20' = n20$mean, '100' = n100$mean, '300' = n300$mean)
tidy(df)
```

```{r}
bin_num <- 15
diff <- 0.4
hi <- ifelse(prop + diff >= 1, 1, prop + diff)
lo <- ifelse(prop - diff <= 0, 0, prop - diff)

ggplot(df) +
  geom_histogram(aes(x = X20), bins = bin_num) +
  scale_x_discrete(limits = c(lo, hi)) +
  theme_bw()
ggplot(df) +
  geom_histogram(aes(x = X100), bins = bin_num) +
  scale_x_discrete(limits = c(lo, hi)) +
  theme_bw()
ggplot(df) +
  geom_histogram(aes(x = X300), bins = bin_num) +
  scale_x_discrete(limits = c(lo, hi)) +
  theme_bw()
```
```{r}
ggplot(df) +
  geom_histogram(aes(x = X300, alpha = 0.1, fill = 'b'), bins = bin_num) +
  geom_histogram(aes(x = X100, alpha = 0.1, fill = 'g'), bins = bin_num) +
  geom_histogram(aes(x = X20, alpha = 0.1, fill = 'r'), bins = bin_num) +
  scale_x_discrete(limits = c(lo, hi)) +
  theme_bw()
```


