```{r}
#simulate groups for KNN
library(tidyverse)
set.seed(1847)
#create data with 4 regions of features
#group1
y1 <- rep(0,20)
x11 <- rnorm(20,30,2)
x12 <- rnorm(20,80,4)  
#group2
y2 <- rep(1,20)
x21 <- rnorm(20,50,2)
x22 <- rnorm(20,80,4)
#group3
y3 <- rep(0,20)
x31 <- rnorm(20,50,2)
x32 <- rnorm(20,60,4)
#group4
y4 <- rep(1,20)
x41 <- rnorm(20,30,2)
x42 <- rnorm(20,60,4)
#combine the regions
y <- c(y1,y2,y3,y4)
x1 <- c(x11,x21,x31,x41)
x2 <- c(x12,x22,x32,x42)

#combine the variables
sim_dat <- as.data.frame(cbind(y,x1,x2))

```
```{r}
ggplot(sim_dat) + geom_point(aes(x=x1,y=x2,color=y))
```

```{r}
#rescale the data 
rescale_x <- function(x){(x-min(x))/(max(x)-min(x))}
new_sim_dat <- sim_dat
new_sim_dat$x1 <- rescale_x(sim_dat$x1)
new_sim_dat$x2 <- rescale_x(sim_dat$x2)
summary(new_sim_dat)

```
```{r}
ggplot(new_sim_dat) + geom_point(aes(x=x1,y=x2,color=y))
```

```{r}
#make a test set
test_x <- as.data.frame(cbind(y=rep(0,10),x1=rnorm(10,50,2),x2=rnorm(10,60,4)))
test_x_plot <- ggplot(test_x,aes(x=x1,y=x2, color=y))+geom_point()+coord_cartesian(xlim=c(20,60),ylim=c(50,90))
test_x_plot

```
```{r}
new_test <- rescale_x(test_x)
new_test_x_plot <- ggplot(new_test,aes(x=x1,y=x2, color=y))+geom_point()
new_test_x_plot

```
```{r}
library(class)
sim_knn <- knn(new_sim_dat[-1]
                    ,test=new_test[-1]
                    ,cl=new_sim_dat$y,k=3)
sim_knn

```

```{r}
table(sim_knn,new_test$y)

```

```{r}
#make a new rescale
rescale_xy <- function(x,y){(x-min(y))/(max(y)-min(y))}
new_test$x1 <- rescale_xy(test_x$x1,sim_dat$x1)
new_test$x2 <- rescale_xy(test_x$x2,sim_dat$x2)
sim_knn <- knn(new_sim_dat[-1]
               ,test=new_test[-1]
               ,cl=new_sim_dat$y,k=3)
summary(sim_knn)
sim_knn

```
```{r}
set.seed(1847)
x1 <- runif(1000, 50, 100)
x2 <- runif(1000, 10, 40)
y <- as.factor(ifelse(x1 > 70 & x2 > 30, 1, ifelse(x1 < 65 & x2 < 25, 0, 2)))

dat <- cbind.data.frame(x1, x2, y)

ggplot(dat) + geom_point(aes(x = x1, y = x2, color = y))


```
```{r}
set.seed(1947)

x1 <- runif(1000, 50, 100)
x2 <- runif(1000, 10, 40)
y <- as.factor(ifelse(x11 > 70 & x21 > 30, 1, ifelse(x11 < 65 && x21 < 25, 0, 2)))



dat_test <- cbind.data.frame('x1' = x11, 'x2' = x21, 'y' = y2)

mod <- knn(train = dat, test = dat_test, y, k=2)

table(y2, mod)
```

```{r}
N <- 20
reclassify <- function(n){
  mods <- list()
  confs <- list()
  pcts <- list()
  for(i in 1:n){
    mod <- knn(train = dat, test = dat_test, y, k=i)
    conf <- table(y2, mod)
    pct <- (conf[1,1] + conf[2,2]) / sum(conf)
    mods[[i]] <- mod
    confs[[i]] <- list( 'confusion_matrix' = conf, 'accuracy' = pct )
  }
  return(list('mods' = mods, 'confs' = confs))
}

rec <- reclassify(N)
rec$confs
```
```{r}
plot(1:N, sapply(rec$confs, '[[', 2))
```

