

```{r}
library(tidyverse)

```

# 0

```{r}
#create data with 4 regions of features
set.seed(1847)
#group1
y1 <- rep(1,40)
x11 <- rnorm(40,300,40)
x12 <- rnorm(40,80,4)  
#group2
y2 <- rep(2,40)
x21 <- rnorm(40,800,40)
x22 <- rnorm(40,80,4)
#group3
y3 <- rep(3,40)
x31 <- rnorm(40,800,40)
x32 <- rnorm(40,60,4)
#group4
y4 <- rep(4,40)
x41 <- rnorm(40,300,40)
x42 <- rnorm(40,60,4)

#combine the regions
yvar <- c(y1,y2,y3,y4)
x1 <- c(x11,x21,x31,x41)
x2 <- c(x12,x22,x32,x42)

#combine the variables
sim_dat0 <- as.data.frame(cbind(yvar,x1,x2))
glimpse(sim_dat0)

```
```{r}
ggplot(sim_dat0) +
  geom_point(aes(x = x1, y = x2, color = as.factor(yvar))) + 
  labs(color = 'yvar') +
  theme_bw()
```

```{r}
#run kmeans
set.seed(1847)
k_ss0 <- rep(0,9)
for(i in 1:9){
  sim_clust0 <- kmeans(sim_dat0,centers=i,nstart=30)
  k_ss0[i] <- sim_clust0$tot.withinss
}
plot(k_ss0)

```

```{r}
sim_clust0 <-kmeans(sim_dat0,centers=2,nstart=30)
table(sim_clust0$cluster,sim_dat0$yvar)

```

```{r}
#run hclustering
sim_dist0 <- dist(sim_dat0[2:3])

```

```{r}
sim_hclust0 <- hclust(sim_dist0,method="complete")
plot(sim_hclust0,cex=0.9)

```

```{r}
sim_dat0$clusters <- cutree(sim_hclust0,4)


cluster_plot0 <- ggplot(sim_dat0,aes(x=x1,y=x2,color=as.factor(clusters)))+geom_point()
cluster_plot0

```

# 1


```{r}
#rescale the data 
sim_dat1 <- sim_dat0
sim_dat1[2:3]<- as.data.frame(lapply(sim_dat1[2:3],scale))
glimpse(sim_dat1)

```

```{r}
ggplot(sim_dat1) +
  geom_point(aes(x = x1, y = x2, color = as.factor(yvar))) + 
  labs(color = 'yvar') +
  theme_bw()
```


```{r}
#run kmeans
set.seed(1847)
k_ss1 <- rep(0,9)
for(i in 1:9){
  sim_clust1 <- kmeans(sim_dat1,centers=i,nstart=30)
  k_ss1[i] <- sim_clust1$tot.withinss
}
plot(k_ss1)

```

```{r}
sim_clust1 <-kmeans(sim_dat1,centers=4,nstart=30)
table(sim_clust1$cluster,sim_dat1$yvar)

```

```{r}
#run hclustering
sim_dist1 <- dist(sim_dat1[2:3])

```

```{r}
sim_hclust1 <- hclust(sim_dist1,method="complete")
plot(sim_hclust1,cex=0.9)

```

```{r}
sim_dat1$clusters <- cutree(sim_hclust1,4)


cluster_plot1 <- ggplot(sim_dat1,aes(x=x1,y=x2,color=as.factor(clusters)))+geom_point()
cluster_plot1
```


```{r}
sim_dist1_0 <- dist(sim_dat1[2:3],method="manhattan")
sim_hclust1_0 <- hclust(sim_dist1_0,method="complete")
plot(sim_hclust1_0,cex=0.9)

```

```{r}
sim_dat1$clusters0 <- cutree(sim_hclust1_0,4)


cluster_plot1_0 <- ggplot(sim_dat1,aes(x=x1,y=x2,color=as.factor(clusters0)))+geom_point()
cluster_plot1_0
```

# 2

```{r}
set.seed(1847)
ddist2 <- data.frame(x1 = rnorm(160, 0, 2), x2 = rnorm(160, 0, 2), y = rep(1, 160))
ggplot(ddist2) + geom_point(aes(x = x1, y = x2, color = y))
```

```{r}
set.seed(1847)
sim_dist2 <- dist(ddist2[2:3])
sim_hclust2 <- hclust(sim_dist2,method="complete")
plot(sim_hclust2,cex=0.9)
```

```{r}
#run kmeans
set.seed(1847)
k_ss2 <- rep(0,9)
for(i in 1:9){
  sim_hclust2 <- kmeans(ddist2,centers=i,nstart=30)
  k_ss2[i] <- sim_hclust2$tot.withinss
}
plot(k_ss2)
```

# 3

```{r}
set.seed(2755)
ddist3 <- data.frame(x1 = rnorm(160, 0, 2), x2 = rnorm(160, 0, 2), y = rep(1, 160))
ggplot(ddist3) + geom_point(aes(x = x1, y = x2, color = y))
```

```{r}
set.seed(2755)
sim_dist3 <- dist(ddist3[2:3])
sim_hclust3 <- hclust(sim_dist3,method="complete")
plot(sim_hclust3,cex=0.9)
```

```{r}
#run kmeans
set.seed(2755)
k_ss3 <- rep(0,9)
for(i in 1:9){
  sim_hclust3 <- kmeans(ddist3,centers=i,nstart=30)
  k_ss3[i] <- sim_hclust3$tot.withinss
}
plot(k_ss3)
```
