---
output:
  pdf_document: default
  html_document: default
---
# Duncan McKinnon
# West
# HW 9


```{r warning=FALSE, message=FALSE}
# Read in packages and data
suppressPackageStartupMessages({
  library(tidyverse)
  library(NHANES)
  library(neuralnet)
})
```

### 1).

```{r}
# Create indicator variable RM1 and Sex1
data <- NHANES %>% 
  mutate(RM1 = ifelse(RegularMarij=="Yes",1,0), Sex1 = ifelse(Gender=="male",1,0))

# Summarize indicators
data %>% 
  select(RM1, Sex1) %>%
  summary()
```

### 2).

```{r warning=FALSE, message=FALSE}
# Limit dataset to HardDrugs, RM1, Age, BMI and Sex1
# Scale Age and BMI to be between 0-1
data <- data %>%
  select(HardDrugs, RM1, Age, BMI, Sex1) %>%
  mutate_at(vars(Age, BMI), funs(scale(.) %>% as.vector))

data %>% glimpse()

```

### 3).

```{r}
# remove missing values
data <- data %>% na.omit()

# get length of remaining columns
data %>% lapply(length)
```

### 4).

```{r}
# Set random seed
set.seed(1847)
p <- 0.2
m <- 4907

# get random indices and split train and test data
train_ind <- sample.int(m, (1-p)*m)
traind <- data[train_ind,]
testd <- data[-train_ind,]

traind %>% glimpse()
testd %>% glimpse()
```

### 5).

```{r}
# Set random seed
set.seed(1847)

# create formula
f <- formula(HardDrugs ~ RM1 + Age + BMI + Sex1)

# fit the NN on the training data
mNN <- neuralnet(f, traind, hidden=1, linear.output=F, rep=10, lifesign="minimal")
```

### 6).

```{r}
# plot network form for result
plot(mNN, rep="best")
```

### 7).

```{r}
# get predictions on test data for the best network result
p1 <- compute(mNN, testd, rep=7)

# create confusion matrix
table(round(p1$net.result[,2]), ifelse(testd$HardDrugs=="Yes",1,0))
```

### 8).

```{r}
# set random seed
set.seed(1847)

# fit the NN on the training data with 2 hidden layers
mNN2 <- neuralnet(f, traind, hidden=2, linear.output=F, rep=10, lifesign="minimal")

```

### 9).

```{r}
# plot network form for result
plot(mNN2, rep="best")
```

### 10).

```{r}
# get predictions on test data for the best network result
p2 <- compute(mNN2, testd, rep=4)

# create confusion matrix
table(round(p2$net.result[,2]), ifelse(testd$HardDrugs=="Yes",1,0))
```

